title: "Mario"
description: "Psychologist and Cybersecurity Specialist"
baseurl: "/profile-site"  
url: "https://mariovalcen.github.io"  # URL actual en GitHub Pages
safe: true  
plugins:
  - jekyll-feed
  - jekyll-seo-tag

exclude:  
  - .git
  - .jekyll-cache
  - _site
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor

