title: "Mario"
description: "Psychologist and Cybersecurity Specialist"
baseurl: ""
url: "https://marwire.eu" 
safe: true  
plugins:
  - jekyll-feed
  - jekyll-seo-tag

exclude:  
  - .git
  - .jekyll-cache
  - _site
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor

